//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class svpEntities : DbContext
    {
        public svpEntities()
            : base("name=svpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<award> award { get; set; }
        public virtual DbSet<club> club { get; set; }
        public virtual DbSet<competition> competition { get; set; }
        public virtual DbSet<disagprofile> disagprofile { get; set; }
        public virtual DbSet<evaluation> evaluation { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<manualprofile> manualprofile { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<participant> participant { get; set; }
        public virtual DbSet<price> price { get; set; }
        public virtual DbSet<profile> profile { get; set; }
        public virtual DbSet<sequence> sequence { get; set; }
        public virtual DbSet<shot> shot { get; set; }
    }
}
