//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class svpEntities : DbContext
    {
        public svpEntities()
            : base("name=svpEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<award> award { get; set; }
        public virtual DbSet<club> club { get; set; }
        public virtual DbSet<competition> competition { get; set; }
        public virtual DbSet<disagprofile> disagprofile { get; set; }
        public virtual DbSet<evaluation> evaluation { get; set; }
        public virtual DbSet<group> group { get; set; }
        public virtual DbSet<manualprofile> manualprofile { get; set; }
        public virtual DbSet<member> member { get; set; }
        public virtual DbSet<participant> participant { get; set; }
        public virtual DbSet<price> price { get; set; }
        public virtual DbSet<profile> profile { get; set; }
        public virtual DbSet<sequence> sequence { get; set; }
        public virtual DbSet<shot> shot { get; set; }
    }
}
