//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shot
    {
        public int Id { get; set; }
        public double Value { get; set; }
        public short ShotNumber { get; set; }
        public double FactorValue { get; set; }
        public double Angle { get; set; }
        public bool Valid { get; set; }
    
        public virtual Sequence Sequence { get; set; }
    }
}
