//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVP
{
    using System;
    using System.Collections.Generic;
    
    public partial class shot
    {
        public int id { get; set; }
        public double value { get; set; }
        public int sequence_id { get; set; }
        public int shot_number { get; set; }
        public double factor_value { get; set; }
        public double angle { get; set; }
        public bool valid { get; set; }
    
        public virtual sequence sequence { get; set; }
    }
}
