//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVP
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SVPEntitiesContainer : DbContext
    {
        public SVPEntitiesContainer()
            : base("name=SVPEntitiesContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Club> Clubs { get; set; }
        public virtual DbSet<Profile> Profiles { get; set; }
        public virtual DbSet<Sequence> Sequences { get; set; }
        public virtual DbSet<Shot> Shots { get; set; }
        public virtual DbSet<Competition> Competitions { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
    }
}
