//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVPMigrator.Old
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class svp_oldEntities1 : DbContext
    {
        public svp_oldEntities1()
            : base("name=svp_oldEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<award> awards { get; set; }
        public virtual DbSet<club> clubs { get; set; }
        public virtual DbSet<competition> competitions { get; set; }
        public virtual DbSet<disagprofile> disagprofiles { get; set; }
        public virtual DbSet<evaluation> evaluations { get; set; }
        public virtual DbSet<group> groups { get; set; }
        public virtual DbSet<manualprofile> manualprofiles { get; set; }
        public virtual DbSet<member> members { get; set; }
        public virtual DbSet<participant> participants { get; set; }
        public virtual DbSet<price> prices { get; set; }
        public virtual DbSet<profile> profiles { get; set; }
        public virtual DbSet<sequence> sequences { get; set; }
        public virtual DbSet<shot> shots { get; set; }
    }
}
