//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SVPMigrator.Old
{
    using System;
    using System.Collections.Generic;
    
    public partial class shot
    {
        public int id { get; set; }
        public double value { get; set; }
        public int shot_number { get; set; }
        public double factor_value { get; set; }
        public double angle { get; set; }
        public bool valid { get; set; }
        public int sequence_id { get; set; }
    
        public virtual sequence sequence { get; set; }
    }
}
