-- MySQL Script generated by MySQL Workbench
-- 03/02/17 16:43:43
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema svp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema svp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `svp` DEFAULT CHARACTER SET utf8 ;
USE `svp` ;

-- -----------------------------------------------------
-- Table `svp`.`club`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`club` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `isTemporary` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`member` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  `shortname` VARCHAR(45) NULL,
  `club_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_member_club_idx` (`club_id` ASC),
  UNIQUE INDEX `shortname_UNIQUE` (`shortname` ASC),
  CONSTRAINT `fk_member_club`
    FOREIGN KEY (`club_id`)
    REFERENCES `svp`.`club` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`profile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`profile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`sequence` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATETIME(6) NULL,
  `member_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shot_member1_idx` (`member_id` ASC),
  INDEX `fk_shot_profile1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_shot_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `svp`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_shot_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `svp`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`competition`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`competition` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `date` DATE NOT NULL,
  `group_competition` TINYINT(1) NOT NULL,
  `sealed` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`evaluation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`evaluation` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `key` VARCHAR(45) NOT NULL,
  `is_group` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`price` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `competition_id` INT NOT NULL,
  `evaluation_id` INT NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_price_competition1_idx` (`competition_id` ASC),
  INDEX `fk_price_evaluation1_idx` (`evaluation_id` ASC),
  INDEX `fk_price_profile1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_price_competition1`
    FOREIGN KEY (`competition_id`)
    REFERENCES `svp`.`competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_evaluation1`
    FOREIGN KEY (`evaluation_id`)
    REFERENCES `svp`.`evaluation` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `svp`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`shot`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`shot` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` DOUBLE NOT NULL,
  `shot_number` INT NOT NULL,
  `factor_value` DOUBLE NOT NULL,
  `angle` DOUBLE NOT NULL,
  `valid` TINYINT(1) NOT NULL,
  `sequence_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_shot_sequence1_idx` (`sequence_id` ASC),
  CONSTRAINT `fk_shot_sequence1`
    FOREIGN KEY (`sequence_id`)
    REFERENCES `svp`.`sequence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`award`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`award` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `competition_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_award_competition1_idx` (`competition_id` ASC),
  CONSTRAINT `fk_award_competition1`
    FOREIGN KEY (`competition_id`)
    REFERENCES `svp`.`competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`participant`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`participant` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`group` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `competition_id` INT NOT NULL,
  `participant_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_group_competition1_idx` (`competition_id` ASC),
  INDEX `fk_group_participant1_idx` (`participant_id` ASC),
  CONSTRAINT `fk_group_competition1`
    FOREIGN KEY (`competition_id`)
    REFERENCES `svp`.`competition` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_participant1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `svp`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`group_has_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`group_has_member` (
  `group_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`group_id`, `member_id`),
  INDEX `fk_group_has_member_member1_idx` (`member_id` ASC),
  INDEX `fk_group_has_member_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_member_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `svp`.`group` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_member_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `svp`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`participant_has_member`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`participant_has_member` (
  `participant_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`participant_id`, `member_id`),
  INDEX `fk_participant_has_member_member1_idx` (`member_id` ASC),
  INDEX `fk_participant_has_member_participant1_idx` (`participant_id` ASC),
  CONSTRAINT `fk_participant_has_member_participant1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `svp`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_has_member_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `svp`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`price_has_winner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`price_has_winner` (
  `price_id` INT NOT NULL,
  `participant_id` INT NOT NULL,
  PRIMARY KEY (`price_id`, `participant_id`),
  INDEX `fk_price_has_participant_participant1_idx` (`participant_id` ASC),
  INDEX `fk_price_has_participant_price1_idx` (`price_id` ASC),
  CONSTRAINT `fk_price_has_participant_price1`
    FOREIGN KEY (`price_id`)
    REFERENCES `svp`.`price` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_price_has_participant_participant1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `svp`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`participant_has_sequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`participant_has_sequence` (
  `participant_id` INT NOT NULL,
  `sequence_id` INT NOT NULL,
  PRIMARY KEY (`participant_id`, `sequence_id`),
  INDEX `fk_participant_has_sequence_sequence1_idx` (`sequence_id` ASC),
  INDEX `fk_participant_has_sequence_participant1_idx` (`participant_id` ASC),
  CONSTRAINT `fk_participant_has_sequence_participant1`
    FOREIGN KEY (`participant_id`)
    REFERENCES `svp`.`participant` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_participant_has_sequence_sequence1`
    FOREIGN KEY (`sequence_id`)
    REFERENCES `svp`.`sequence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`sequence_has_newSequence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`sequence_has_newSequence` (
  `sequence_id` INT NOT NULL,
  `newSequence_id` INT NOT NULL,
  PRIMARY KEY (`sequence_id`, `newSequence_id`),
  INDEX `fk_sequence_has_sequence_sequence2_idx` (`newSequence_id` ASC),
  INDEX `fk_sequence_has_sequence_sequence1_idx` (`sequence_id` ASC),
  CONSTRAINT `fk_sequence_has_sequence_sequence1`
    FOREIGN KEY (`sequence_id`)
    REFERENCES `svp`.`sequence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_sequence_has_sequence_sequence2`
    FOREIGN KEY (`newSequence_id`)
    REFERENCES `svp`.`sequence` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`disagProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`disagProfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `value` VARCHAR(45) NOT NULL,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_disagProfile_profile1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_disagProfile_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `svp`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`manualProfile`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`manualProfile` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `profile_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_manualProfile_profile1_idx` (`profile_id` ASC),
  CONSTRAINT `fk_manualProfile_profile1`
    FOREIGN KEY (`profile_id`)
    REFERENCES `svp`.`profile` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `svp`.`award_has_winner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `svp`.`award_has_winner` (
  `award_id` INT NOT NULL,
  `member_id` INT NOT NULL,
  PRIMARY KEY (`award_id`, `member_id`),
  INDEX `fk_award_has_member_member1_idx` (`member_id` ASC),
  INDEX `fk_award_has_member_award1_idx` (`award_id` ASC),
  CONSTRAINT `fk_award_has_member_award1`
    FOREIGN KEY (`award_id`)
    REFERENCES `svp`.`award` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_award_has_member_member1`
    FOREIGN KEY (`member_id`)
    REFERENCES `svp`.`member` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
